### ISSUE TITLE
[Feature Request] Run Markdown block API on demand

### ISSUE THREAD

**Issue by sbhal** [Rooyca/obsidian-api-request#10]
When working with markdown blocks that contain API requests, is it possible to have an option to explicitly execute the API request instead of having it run automatically, similar to how the `obsidian-execute-code` plugin allows you to selectively run code blocks?

**Comment by sbhal** [comment]
Alternatively a `disable` flag can be added to markdown block to disable API call.

**Comment by Rooyca** [comment]
I think adding the flag is the most viable option at the moment.

**Comment by Rooyca** [comment]
Hey @sbhal,
Maybe later I will add the button to run the requests on demand, for now the `disabled` flag will prevent the request from running continuously.

**Comment by Rooyca** [comment]
Hello @sbhal,
I felt that the previous solution to this problem fell a little short and didn't make much sense (at least not to me), although disabling the code block works there are cases where you need the answer. This is why now the responses can be stored in `localStorage` by means of the `req-id` flag. Here is an example:

```req
url: https://jsonplaceholder.typicode.com/users/1
show: id
req-id: idUser
disabled
```

This only will run ones. After that will check the `localStorage` for a response.
