### ISSUE TITLE
Failure to Parse Multiple {} Variables in HTML Parameters

### ISSUE THREAD

**Issue by tlwt** [Rooyca/obsidian-api-request#11]
**Description:**
The issue arises when attempting to parse multiple {} variables within HTML parameters. While the plugin successfully handles single {} variables, it encounters errors when multiple variables are present.

**Examples:**

1. **Working Example 1:**
   ```markdown
   show: data -> 0 -> hash_id
   format: <a href="https://monica/people/{}">link</a>
   ```
   this outputs a working link to the contact.

2. **Working Example 2:**
   ```markdown
   show: data -> 0 -> first_name
   format: <a href="https://monica/people/someHashLink">{}</a>
   ```
   this output the correct link name.

3. **Issue Example:**
   ```markdown
   show: data -> 0 -> hash_id, data -> 0 -> first_name
   format: <a href="https://monica/people/{}">{}</a>
   ```
   this outputs just `">Kay`

In the provided examples, the plugin fails to correctly parse multiple {} variables within HTML parameters. While single variables function properly, attempting to incorporate more than one results in parsing errors.

**Comment by Rooyca** [comment]
Thanks for letting me know about this. I think it's fix now.

**Comment by tlwt** [comment]
Awesome again - it is working correctly now.
