### ISSUE TITLE
Tries to parse markdown as JSON, fails

### ISSUE THREAD

**Issue by iodrift** [Rooyca/obsidian-api-request#17]
**Describe the bug**
I have a custom private API script for tracking my billable hours, which includes an endpoint that outputs my timeslips for the day in a neatly formatted markdown table. APIRequest doesn't seem able to parse it as markdown, instead consistently failing with `Error: Unexpected token '|', " |Project|T"... is not valid JSON`

**To Reproduce**

I can't share my actual timekeeping API but I set up a dummy script to illustrate the problem:

```
curl https://temp.sij.law/table

| ID | Name      | Email            |
|----|-----------|------------------|
| 1  | John Doe  | johndoe@mail.com |
| 2  | Jane Smith| janes@mail.com   |
```

^ all well and good, but:

```
` ` ` req
url: https://temp.sij.law/table
response-type: md
` ` `
```

yields this: `Error: Unexpected token '|', " | ID | Nam"... is not valid JSON`. Feel free to test it using that URL, I'll keep it online for a bit.

**Expected behavior**
A markdown table would appear.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 14.4.1

**Additional context**
I also tried changing the API to wrap the markdown in a {"markdown": {{markdown_content}}} JSON output, and tell APIRequest to show the contents of "markdown". It does show the contents, but just as a block of text, `\n` and all -- not properly formatted markdown.

**Comment by Rooyca** [comment]
Hey @iodrift,
I believe is done! Please tell me if it works to you.

**Comment by iodrift** [comment]
Thank you for responding so quickly! Unfortunately I'm still getting the same error.

This is the correct syntax, right?

```req
url: https://temp.sij.law/table
response-type: md
```

**Comment by Rooyca** [comment]
> yes! it works now. 

Glad to hear that.

> Thank you very much for the very quick fix :)

My pleasure. :smile:
