### ISSUE TITLE
Plugin cannot be installed

### ISSUE THREAD

**Issue by joethei** [Rooyca/obsidian-api-request#19]
Hi @Rooyca

We have noticed that the latest release of your plugin cannot be installed currently.

This is due to the following reason(s):
- No release found for version 1.2.4

We will remove this plugins from the community plugins if this issue is not fixed within 30 days.

– The Obsidian Team

**Comment by Rooyca** [comment]
Hey @joethei
Thanks for letting me know, i forget to publish the new release. It's working now.
