### ISSUE TITLE
Basic auth not working 

### ISSUE THREAD

**Issue by bryceprutsos** [Rooyca/obsidian-api-request#21]
**Describe the bug**
When using a basic auth Get request it comes back as 401 error even though it comes back successful in Postman

**To Reproduce**

**Expected behavior**
Come back with information 

**Screenshots**
Obsidian Code
![image](https://github.com/Rooyca/obsidian-api-request/assets/74235158/4beb8427-f3fc-4ccc-8f37-8758e8987a0c)
Postman Code
![image](https://github.com/Rooyca/obsidian-api-request/assets/74235158/53a2a0dc-9c62-414c-91d9-c9587d4a9d3c)

![image](https://github.com/Rooyca/obsidian-api-request/assets/74235158/eedc62a8-3020-4171-9b95-ffeb8b97f61d)

**Additional context**
These calls seem the exact same but I am not sure why I am getting a 401.

**Comment by Rooyca** [comment]
I believe the problem is a missing space after `headers`:

~~~markdown
```req
url: ...
headers: {...} 
```
~~~

P.S. I'll fix this in the next update. Sorry about that.

**Comment by bryceprutsos** [comment]
Yes that was right thanks for helping I was trying all sorts of stuff before putting in this bug. Quick question for the future if I had multiple headers like having to add "Accept": "application/json" as well how would that look in the call?

**Comment by Rooyca** [comment]
This is something that needs to be fix. Thanks for letting me know.

> if I had multiple headers like having to add "Accept": "application/json" as well how would that look in the call?

It should looks something like:

~~~markdown
```req
url: https://example.com
headers: {"Accept": "application/json", "Authorization": "Basic XXXXX"}
```
~~~
I think so... if that doesn't work try removing the space after the comma.

Either way I'll be addressing this problem (spaces, or not spaces, that is the question) in the next release.

**Comment by Rooyca** [comment]
Hey @bryceprutsos,
It should be fix now. Could you check?
