### ISSUE TITLE
{{this.file.name}} not available within query

### ISSUE THREAD

**Issue by tlwt** [Rooyca/obsidian-api-request#22]
**Describe the bug**
I want to use the file name as a parameter for the query, but it does not seem to be passed to the query. Seems to be empty to the query.

**To Reproduce**
1. query some endpoint url: https://example.com?query={{this.file.name}}

**Expected behavior**
Return the dataset matching the file name

**Screenshots**
n.a.

**Desktop (please complete the following information):**
Mac OS X, Obsidian 1.6.3, ApiRequst 1.2.9

**Additional context**
n.a.

**Comment by Rooyca** [comment]
That shouldn't work because currently `{{this.VARNAME}}` only takes into account the front-matter and I think `{{this.file.name}}` it's a dataview functionality.

**Comment by tlwt** [comment]
Oh, you are absolutely right!

any chance to integrate something like that?

**Comment by Rooyca** [comment]
Sure, be right back.

**Comment by Rooyca** [comment]
It's done @tlwt,
Could you check?

**Comment by elvarb** [comment]
Can confirm this works 💪

**Comment by Rooyca** [comment]
Closing as completed.
