### ISSUE TITLE
[Feature Request] Multiple API items and hotkeys

### ISSUE THREAD

**Issue by eb2ai** [Rooyca/obsidian-api-request#3]
I hope we will eventually be able to define multiple APIs in settings and associate each with a hotkey.

I love the idea of typing along, hitting a hotkey, and automatically inserting all the weather, backup status, uptime of a server, current score of the game, etc, etc, etc.

**Comment by Rooyca** [comment]
This one is a bit tricky, but we could give it a try. 
The first thing that comes to my mind would be to use something like `Ctrl+A` that displays a menu with all the configured apis and you can choose the one you want to insert in the document. 
I don't know... I will check if it can be done the way you say.

**Comment by eb2ai** [comment]
I haven't done any programming in this realm, but I think you could look at a couple of other apps that do this well. Quick Add comes to mind.

**Comment by Rooyca** [comment]
Where can I look that app? Can you send me the link?

I appreciate you find use for this

**Comment by eb2ai** [comment]
[Quick Add](https://github.com/chhoumann/quickadd)

**Comment by Rooyca** [comment]
Thanks, I'll check it tomorrow

**Comment by Rooyca** [comment]
It was as complicated as I thought at first but I managed to make it work, of course it is not the most aesthetically pleasing, but it works. If you want to try it you can update your plugin.

PS: I also removed the `json::` part :)

Regards.
