### ISSUE TITLE
codeblock can't be used

### ISSUE THREAD

**Issue by wfeng1982** [Rooyca/obsidian-api-request#33]
![image](https://github.com/user-attachments/assets/344f5baf-64ad-43cd-ad2e-7882c921e59c)

![image](https://github.com/user-attachments/assets/2814e790-c838-416c-ad79-b23d9fc4c69d)

**Comment by wfeng1982** [comment]
version is the latest,1.4.0

**Comment by Rooyca** [comment]
I don't understand. What is wrong with it?

**Comment by Rooyca** [comment]
That sections is not for codeblocks. Codeblocks are explained on [the documentation](https://rooyca.github.io/obsidian-api-request/en/codeblocks/).

**Comment by wfeng1982** [comment]
> I don't understand. What is wrong with it?

The picture shows that only apiRsetting is available. There is no place to input the codeblock.But I want to use the codeblock

**Comment by Rooyca** [comment]
You should read [the documentation](https://rooyca.github.io/obsidian-api-request/en/codeblocks/). For using code-blocks you need to declare the request in your notes, for example:
~~~markdown
```req
url: https://jsonplaceholder.typicode.com/users
```
~~~
There are many flags that can be used with codeblocks; as I said, you should read the documentation.

**Comment by wfeng1982** [comment]
> You should read [the documentation](https://rooyca.github.io/obsidian-api-request/en/codeblocks/). For using code-blocks you need to declare the request in your notes, for example:
> 
> ```
> ```req
> url: https://jsonplaceholder.typicode.com/users
> ```
> ```
> 
> There are many flags that can be used with codeblocks; as I said, you should read the documentation.

3ks,I just know it. it's easy to use.

but I still have one problem.
```req 
url: https://api.bestblogs.dev/api/resource/list
method: post
body: {"keyword": "","qualifiedFilter": "true","sourceId": "","category": "","timeFilter": "1d","language": "all","userLanguage": "zh","sortType":"score_desc","currentPage": 1,"pageSize": 10}
headers: {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36","User-Id": "VU_560dca","Accept-Encoding": "gzip, deflate, br, zstd","Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8","Connection": "keep-alive","Content-Length": "176","Content-Type": "application/json","Origin": "https://www.bestblogs.dev","Referer": "https://www.bestblogs.dev/"}
```
this will occur exception "Error: net::ERR_INVALID_ARGUMENT", because the reponse was the json that the key is enclosed by single quote. In python ,I can use eval and json.dumps func to do it .using apirequest how can I do ?

**Comment by wfeng1982** [comment]
> You should read [the documentation](https://rooyca.github.io/obsidian-api-request/en/codeblocks/). For using code-blocks you need to declare the request in your notes, for example:
> 
> ```
> ```req
> url: https://jsonplaceholder.typicode.com/users
> ```
> ```
> 
> There are many flags that can be used with codeblocks; as I said, you should read the documentation.

3ks,I just know it. it's easy to use.

but I still have one problem.
```req 
url: https://api.bestblogs.dev/api/resource/list
method: post
body: {"keyword": "","qualifiedFilter": "true","sourceId": "","category": "","timeFilter": "1d","language": "all","userLanguage": "zh","sortType":"score_desc","currentPage": 1,"pageSize": 10}
headers: {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36","User-Id": "VU_560dca","Accept-Encoding": "gzip, deflate, br, zstd","Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8","Connection": "keep-alive","Content-Length": "176","Content-Type": "application/json","Origin": "https://www.bestblogs.dev","Referer": "https://www.bestblogs.dev/"}
```
this will occur exception "Error: net::ERR_INVALID_ARGUMENT", because the reponse was the json that the key is enclosed by single quote. In python ,I can use eval and json.dumps func to do it .using apirequest how can I do ?

**Comment by Rooyca** [comment]
The problem seems to be this header: `"Content-Length": "176"`. Just remove it.

**Comment by wfeng1982** [comment]
> The problem seems to be this header: `"Content-Length": "176"`. Just remove it.

thanks!
