### ISSUE TITLE
"show: " does nothing

### ISSUE THREAD

**Issue by kerberoid** [Rooyca/obsidian-api-request#39]
Hi,
I am using your plugin in Obsidian V1.7.7 on Windows11

my query looks like this:

\```req
url: https://NAMEOFMYSERVER:443/api.aspx?Action=GetTicket&key=MYKEY&TicketID=1234
show: TicketID, Description
\```
no matter what I change with show: , it does not affect my output.

The reply of the server looks like this:
```
{"TicketID":1234,"Subject":"example Subject","Description":"HTML with description","CreationDate":"2024-11-21T07:34:54.087","Type":"IT Support","Priority":"Low","State":"Open","Team":"IT Support","Agent":"me","AgentID":4321,"User":"Name of Requester","UserID":1337,"FollowUp":false,"Success":true,"Message":"Ticket has been found"}
``` 

Is this an issue with the plugin or with my query?

**Comment by Rooyca** [comment]
Hello @kerberoid, 
Everything seems fine on my end; I tested with [JSON Placeholder](https://jsonplaceholder.typicode.com/todos/1) with the following querry:

~~~markdown
```req
url: https://jsonplaceholder.typicode.com/todos/1
show: id, title
```
~~~

Maybe the response from your server is not a valid JSON response?

**Comment by kerberoid** [comment]
Maybe. the server response I posted before looks like it is missing the spaces?
If thats it, then It's an issue with the server I have to work with.
