### ISSUE TITLE
Option to hide the "copy" button. 

### ISSUE THREAD

**Issue by orrd** [Rooyca/obsidian-api-request#40]
It would be great if there was a setting to hide the "copy" button.  If there isn't currently a way to do this, I may see if I can manage to figure how to implement that and submit it as a pull request.

**Comment by Rooyca** [comment]
Hello @orrd,
Currently there is no such function, but if you want to implement it that would be great. Feel free to create the PR. :smile:

**Comment by orrd** [comment]
So, I did a clone of the repo and built it with npm, and then when I tried it just as-is like that, it now shows the "copy" button on the top right corner and only when I mouse-over the block (which is a nice improvement!).   With the one that I had installed from Community Plugins, it has been showing the "copy" button at the bottom of the block and it appears all the time there, which was why I found it annoying. 

I think they're both using the same code version I believe.  So I can't figure out why the behavior is different with the copy I built from the Git repo.

**Comment by Rooyca** [comment]
Well, that's weird jaja. Do you have your plugin up to date?

**Comment by orrd** [comment]
Yeah, I had just installed it for the first time last week.  If it's a CSS glitch or something, I don't know whether just restarting Obsidian would have maybe fixed it.

**Comment by Rooyca** [comment]
You are completely right! I just forgot to add the `style.css` file in the release. Is fixed in the new release :smile:
