### ISSUE TITLE
[Feature Request] Post files

### ISSUE THREAD

**Issue by weekdaycare** [Rooyca/obsidian-api-request#8]
Does Data to send support files? As I want to upload my pic to picbed by APIRequest.

> Awsome Plugin

**Comment by Rooyca** [comment]
> Does Data to send support files? 

Not sure, maybe if you convert the image into base64.

**Comment by weekdaycare** [comment]
In this case, I also need to convert the image to base64 first, which will be complicated.
headers
```json
{ "Content-Type": "multipart/form-data", "Authorization": "Bearer token"}
```
When I drag a image or insert a image into obsidian, it can be used as a request parameter (Body) to automatically post the apirequest to upload and return the image link.

**Comment by Rooyca** [comment]
I don't see me working on this... at least not for now. Sorry.
