### ISSUE TITLE
[Feature request] use yaml properties in query

### ISSUE THREAD

**Issue by tlwt** [Rooyca/obsidian-api-request#9]
it would be great if the plugin could support dynamic requests with references to yaml properties

e.g. if in `=this.name` the value `John Doe`

Then something like 
```
url: https://app.monicahq.com/api/contacts?query={{this.name}}
```

would cause a query to

```
url: https://app.monicahq.com/api/contacts?query=John Doe
```

Especially with the dynamic templates this would allow inclusion of very detailed information into obsidian.

**Comment by Rooyca** [comment]
Hey,
I like this idea but can you elaborate a little bit more? Where the variables would be define?

**Comment by tlwt** [comment]
In Obsidian you can define variables within the markdown file. 

Just copy & paste the markdown below (or use this file [Demo Variables.md](https://github.com/Rooyca/obsidian-api-request/files/15072184/Demo.Variables.md)) to an obsidian file and if you change to reading view you will the the resolved variables.

```markdown
---
variable_name: Value of the variable
another_var: TestValue
first_name: Till
---

Just copy & paste this content to obsidian.

`=this.variable_name` 

Best regards, `=this.first_name`
```

**Comment by Rooyca** [comment]
It doesn't work for me. Variables are not replaced.

![preview](https://github.com/Rooyca/obsidian-api-request/assets/42101257/0eade81d-b5d4-4cd4-a7b9-a4c80326e149)
